apiVersion: apps/v1
kind: Deployment
metadata:
  name: justyr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: justyr
  template:
    metadata:
      labels:
        app: justyr
    spec:
      containers:
      - image: okteto.dev/justyr:latest
        name: justyr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: AUUID
          value: "cfb7ee1f-0857-4c86-be94-b1910712dec4"
